[package]
name = "schema_convert"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.1", features=["derive"] }
serde = "1.0.145"
serde_json = "1.0.85"
arrow = "23.0.0"
anyhow = "1.0.65"
insta = "1.21.0"